[package]
name = "webmocket"
version = "0.1.0"
edition = "2021"

[features]
default = ["serde_json", "tokio-tungstenite"]
tokio-tungstenite = ["dep:tokio-tungstenite"]
serde_json = ["dep:serde_json"]

[dependencies]
serde_json = { version = "1.0.133", optional = true }
tokio-tungstenite = { version = "0.24.0", optional = true }
tungstenite = "0.24.0"

[dev-dependencies]
futures = "0.3.31"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
