[package]
name = "webmocket"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-tungstenite = { version = "0.24.0", optional = true }
tungstenite = "0.24.0"

[features]
tokio-tungstenite = ["dep:tokio-tungstenite"]
